Repository sociomantic-tsunami/dhtproto, pull requests merged in 2018-04, with the labels that each got.

#129 Add new helper class to wrap RetryHandshake with task support
  relnotes/handshake.feature.md
  src/dhtproto/client/legacy/internal/helper/Handshake.d
Labels: type-feature

#137 Convert assert -> verify
  src/dhtproto/client/DhtClient.d
  src/dhtproto/client/legacy/common/NodeRecordBatcher.d
  src/dhtproto/client/legacy/internal/RequestSetup.d
  src/dhtproto/client/legacy/internal/connection/DhtNodeConnectionPool.d
  src/dhtproto/client/legacy/internal/connection/DhtRequestConnection.d
  src/dhtproto/client/legacy/internal/helper/ExtensibleChannelMirror.d
  src/dhtproto/client/legacy/internal/helper/Handshake.d
  src/dhtproto/client/legacy/internal/helper/mirror/ContiguousRecordCache.d
  src/dhtproto/client/legacy/internal/helper/mirror/model/MirrorBase.d
  src/dhtproto/client/legacy/internal/registry/DhtNodeRegistry.d
  src/dhtproto/client/legacy/internal/request/ExistsRequest.d
  src/dhtproto/client/legacy/internal/request/notifier/RequestNotification.d
  src/dhtproto/node/request/model/CompressedBatch.d
  src/dhtproto/node/request/model/DhtCommand.d
Labels: type-refactoring

#139 Make DhtClient.DhtConnNotification public
  src/dhtproto/client/mixins/NeoSupport.d
Labels: type-bug

#136 Add built-in logging to RetryHandshake
  relnotes/retryhandshake-logging.feature.md
  src/dhtproto/client/legacy/internal/helper/RetryHandshake.d
Labels: type-feature
